### ISSUE TITLE
RuntimeException: Connection timed out

### ISSUE THREAD

**Issue by atlanticmanagement** [clue/reactphp-socks#94] opened 2020-07-19 15:39 UTC
Hi, I tried your class, but I don't get it to work. My plan is to connect to a socks5 proxy.
```

use Clue\React\Socks\Client;
use React\Socket\Connector;
use React\Socket\ConnectionInterface;

require __DIR__ . '/plugins/Proxy/vendor/autoload.php';

$proxy_ip 	= 'MYPSOCKSROXYIP';
$proxy_port	= '3001';
$proxy_user	= 'MYUSERNAME';
$proxy_pass	= 'MYPASS';
$loop = React\EventLoop\Factory::create();

$proxy = 'socks5://'.$proxy_user.':'.$proxy_pass.'@'.$proxy_ip.':'.$proxy_port;

$loop = React\EventLoop\Factory::create();

$client = new Client($proxy, new Connector($loop));
$connector = new Connector($loop, array(
    'tcp' => $client,
    'timeout' => 3.0,
    'dns' => false
));

echo 'Demo SOCKS client connecting to SOCKS server ' . $proxy . PHP_EOL;

$connector->connect('tcp://www.google.com:80')->then(function (ConnectionInterface $stream) {
    echo 'connected' . PHP_EOL;
    $stream->write("GET / HTTP/1.0\r\n\r\n");
    $stream->on('data', function ($data) {
        echo $data;
    });
}, 'printf');

$loop->run();

```

But I only get this answer if I run the script:

```
Demo SOCKS client connecting to SOCKS server socks5://MYUSERNAME:MYPASS@MYPSOCKSROXYIP:3001 RuntimeException: Connection to tcp://www.google.com:80 timed out after 3 seconds in /var/www/vhosts/mydomain.com/httpdocs/app/plugins/Proxy/vendor/react/socket/src/TimeoutConnector.php:41 Stack trace: #0 /var/www/vhosts/mydomain.com/httpdocs/app/plugins/Proxy/vendor/react/promise/src/RejectedPromise.php(28): React\Socket\TimeoutConnector::React\Socket\{closure}() #1 /var/www/vhosts/mydomain.com/httpdocs/app/plugins/Proxy/vendor/react/promise/src/Promise.php(134): React\Promise\RejectedPromise->then() #2 /var/www/vhosts/mydomain.com/httpdocs/app/plugins/Proxy/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}() #3 /var/www/vhosts/mydomain.com/httpdocs/app/plugins/Proxy/vendor/react/promise/src/Promise.php(148): React\Promise\Promise->settle() #4 /var/www/vhosts/mydomain.com/httpdocs/app/plugins/Proxy/vendor/react/promise/src/Promise.php(237): React\Promise\Promise->reject() #5 /var/www/vhosts/mydomain.com/httpdocs/app/plugins/Proxy/vendor/react/promise-timer/src/functions.php(47): React\Promise\Promise::React\Promise\{closure}() #6 /var/www/vhosts/mydomain.com/httpdocs/app/plugins/Proxy/vendor/react/event-loop/src/Timer/Timers.php(96): React\Promise\Timer\{closure}() #7 /var/www/vhosts/mydomain.com/httpdocs/app/plugins/Proxy/vendor/react/event-loop/src/StreamSelectLoop.php(184): React\EventLoop\Timer\Timers->tick() #8 /var/www/vhosts/mydomain.com/httpdocs/app/test.php(38): React\EventLoop\StreamSelectLoop->run() #9 {main}
```

I hav checked the socks5 proxy. Is full working if I test it for example in firefox.

**Comment by clue** [comment] 2020-07-20 16:26
@atlanticmanagement Thanks for reporting and welcome to this project! :rocket: 

I've just tried to reproduce this locally and can not reproduce the problem you're seeing. We're not aware of any problems with this library and everything seems to be working as expected.

The error suggests your proxy server or your destination server did not respond within 3 seconds, so this might as well be a temporary network load or latency issue. Have you tried using a different (higher) timeout value?

Have you tried testing your proxy credentials with any other tool? You mentioned Firefox, are you sure you've verified this with the given login credentials? (To my knowledge, Firefox still does not support SOCKS authentication by default.)

If you can share your credentials, drop me a mail and I'm happy to take a look from my end.

**Comment by clue** [comment] 2020-09-24 06:22
I'm closing this for now as it hasn't received any input in a while and I believe this has been answered. Please come back with more details if this problem persists and we can reopen this :+1:

**Closed by clue** 2020-09-24 06:22 UTC
Labels: help wanted, question
